### ISSUE TITLE
Pickup lights pop away sometimes

### ISSUE THREAD

**Issue by jniemibro** [Tayrtahn/ggj2022#20]
I noticed once a certain amount of pickups appear, lights start to pop away. 

We could switch to deferred rendering allowing more light sources or we could make our own faked light/halo/bloom effect. We could also increase the max allowed light sources in QualitySettings, I think...

**Comment by Tayrtahn** [comment]
To my eye, the pickups look fine without a light source on them. A little extra bloom might be nice; maybe we can crank up the emissive color intensity?

**Comment by jniemibro** [comment]
I don't think this is an issue any longer as we've switched to deferred rendering. All pickup lights appear to stay regardless of amount.

**Comment by Tayrtahn** [comment]
Yep, marking as closed
